apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shop
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: http
      port: 80          # cổng Service trong cluster
      targetPort: 80    # cổng container trong Pod
      nodePort: 30080   # cổng mở trên Node (30000–32767). Có thể bỏ dòng này để K8s tự cấp.