apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shop
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
    
