apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: thanh2909/simple-fullstack-docker-v3-ci-tests-api:v0.4
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef: { name: backend-secrets }
          
            # Thêm các env khác bạn dùng trong FastAPI (JWT_SECRET, etc.)
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: shop
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
