apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: thanh2909/simple-fullstack-docker-v3-ci-tests-frontend:v0.2
          ports:
            - containerPort: 80
          env:
            # Quan trọng: frontend cần biết API_BASE runtime
            # Nếu bạn dùng window.__ENV__ pattern, bạn có thể bỏ qua biến này ở container
            # và thay bằng reverse proxy /api → api service ở bước 7,
            # thì FE chỉ gọi relative path "/api".
            - name: API_BASE
              value: /api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shop
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
