apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-nginx-conf
  namespace: shop
data:
  nginx.conf: |
    worker_processes auto;
    events { worker_connections 1024; }

    http {
      client_max_body_size 50m;

      upstream frontend_upstream {
        server frontend.shop.svc.cluster.local:80;
        keepalive 16;
      }

      upstream api_upstream {
        server api.shop.svc.cluster.local:8000;
        keepalive 16;
      }

      upstream minio_upstream {
        server minio.shop.svc.cluster.local:9000;
        keepalive 16;
      }

      server {
        listen 80;
        server_name _;

        # Frontend (SPA)
        location / {
          proxy_pass http://frontend_upstream;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # API backend
        location /api/ {
          proxy_pass http://api_upstream/;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # MinIO S3 / console (tùy bạn muốn expose path nào)
        location /minio/ {
          proxy_pass http://minio_upstream/;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: proxy-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: proxy-conf
          configMap:
            name: proxy-nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: shop
spec:
  selector:
    app: proxy
  type: NodePort
  ports:
    - name: http
      port: 80        # cluster port
      targetPort: 80  # container port
      nodePort: 30080 # external port on each worker node
