apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shop
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30081
  type: NodePort
