apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2024-06-13T22-53-53Z
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9000   # API
            - containerPort: 9001   # Web console
          envFrom:
            - secretRef:
                name: minio-secrets
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pvc
